services:
  bot:
    image: python:latest
    container_name: discord_matching_bot_python
    restart: always
    working_dir: /app/src
    volumes:
      - ../../src:/app/src  # Mounts only the src folder into the container
      - ../scripts/entrypoint.sh:/entrypoint.sh # Mounts the entrypoint script
      - ../../config/other_configs/requirements.txt:/app/requirements.txt # Mounts requirements.txt
    command: ["/bin/bash", "-c", "chmod +x /entrypoint.sh && /entrypoint.sh"]
