version: '3.8'

services:
  python-app:
    image: python:latest
    container_name: python_container
    restart: always
    working_dir: /app
    volumes:
      - ../../:/app
      - ../scripts/entrypoint.sh:/entrypoint.sh
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    command: ["/bin/bash", "-c", "chmod +x /entrypoint.sh && /entrypoint.sh"]
