name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - docker/discord-bot/Dockerfile
      - .github/workflows/docker-image.yml
      - docker/scripts/entrypoint.sh
      - src/bot.py
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Repository Owner to Lowercase
        id: repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_GUTHUB }}

      - name: Build Docker Image
        run: |
          docker build \
            --tag ghcr.io/${{ env.REPO_OWNER }}/discord-matching-bot:${{ github.sha }} \
            --tag ghcr.io/${{ env.REPO_OWNER }}/discord-matching-bot:latest \
            -f docker/discord-bot/Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER }}/discord-matching-bot:${{ github.sha }}
          docker push ghcr.io/${{ env.REPO_OWNER }}/discord-matching-bot:latest
