name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_GUTHUB }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner.lower() }}/discord-matching-bot:latest -f docker/discord-bot/docker-compose.yml .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner.lower() }}/discord-matching-bot:latest
